### ISSUE TITLE
Instants get serialized as with reduced precision instead of using the ExtendedIsoFormat

### ISSUE THREAD

**Issue by crazycrank** [AndyBeverlySchool/MongoDb.Bson.NodaTime#14]
We realized in our application that we loose precision in the MongoDB when we store instants using the MongopDb.Bson.NodaTime serializers.

The culprit is specifically the class https://github.com/AndyBeverlySchool/MongoDb.Bson.NodaTime/blob/master/src/MongoDb.Bson.NodaTime/InstantSerializer.cs, which uses `context.Writer.WriteDateTime(value.ToUnixTimeTicks() / 10000L);` to serialize the instant. 

The InstantSerializer is also the only serializer to implement the Serialize/Deserialize methods directly instead of using the PatternSerializer base class. The PatternSerializer also uses `context.Writer.WriteString(this.pattern.Format(this.valueConverter(value)));` to serialize (instead of `WriteDateTime`) whereas `this.pattern` is set to use the `ExtendedIso` pattern everywhere where time values get serialized.

The InstantSerializer should be refactored to also use the PatternSerializer base class, or at least be changed to `WriteString` with the correct IseExtended pattern

**Comment by crazycrank** [comment]
See the attached PR :)

**Comment by crazycrank** [comment]
**Ignore this comment, I've just seen your comment on the PR :)**

Hey @tetious , is there any chance this will get merged this week? we're having a nasty bug in our system which depends on this, and our go-live is in two weeks 😃 Otherwise we need to fix this on our side

Best,
Max

**Comment by tetious** [comment]
I plan to merge it today or tomorrow, so no worries there!

**Comment by tetious** [comment]
After poking at this a bit, I don't think I can merge this as is. I now remember why I did it this way. :)

Instants are presently serialized to be compatible with Mongo's underling Date representation, which is [limited to ms precision](https://docs.mongodb.com/manual/reference/bson-types/#document-bson-type-date) and is represented in the BSON as "a 64-bit integer that represents the number of milliseconds since the Unix epoch (Jan 1, 1970)."

Your implementation serializes the field as a string. This is why you had to remove the ISODate wrapper from the converted values in the tests. It appears to work for the simple cases covered in the unit tests, but breaks down when you expect the type to be a Date mongo-side. This will probably break server-side sorting, date comparisons/diffs, and many other things with queries. I really should get around to adding some integration tests that exercise these features.

If your use-case only needs Instants to keep their precision, and will never query against them (except as strings, so basically equality only), it would probably be better to be explicit about this, and use strings in your documents. Otherwise things get very confusing. 

I hope this makes sense! Please let me know what you think.

**Comment by crazycrank** [comment]
Yeah I was actually aware of that, but I didn't think this was an issue.

So, all NodaTime types have the same precision as an Instant. If I'm not mistaken, this holds true for LocalDateTime, LocalTime, OffsetDateTime, ZonedDateTime and should also hold true for Periods and Durations.
Right now, all types except Instant get serialized to MongoDb as a string (correct me if I'm wrong. But I think the PatternSerializer always stores to the DB as a string, right?).

Especially for all the DateTime values you could IMHO make the same argument to have them be stored using MongoDBs Date Representation, but they are right now stored using a string - I was assuming this was for the exact reason of keeping the precision there. 

I think this is an inconsistency in the current implementation of the serializers. They should either all keep the precision high and get stored as strings - or none of them should and all values that make sense (all DateTime values and the Instant) be stored as MongoDB DateTimes. But this then would lead to an inconsistency compared to Period and Duration, as well as LocalTime, as these would still be stored as strings and hence with the higher precision.

A solution to this dilemma could be to make this behavior configurable, and depending on that use either the DateTime or the string representation, but this would probably be a rather, maybe even breaking change?

What's your thoughts on that?

**Comment by tetious** [comment]
I do see your point, though I'd argue it would make more sense to switch as many things away from strings as possible, as that would be less surprising when attempting to query in ways that you'd probably like to be able to do with dates. This project evolved in that way they often do, in that I wrote it to work how we needed it, and didn't always make forward-looking decisions. ;)

We can start for now with making Instant configurable. I like that approach. As long as it defaults to current behavior, seems pretty low risk to me.

I'll take a quick stab at it this morning and add you to the PR.

**Comment by tetious** [comment]
Please have a look at https://github.com/AndyBeverlySchool/MongoDb.Bson.NodaTime/pull/17 and let me know what you think.

**Comment by crazycrank** [comment]
I think this looks pretty good with our current assumption. Making it configurable is most certainly the way to go.

What I do wonder a little bit is if our assumptions are correct. I did some research and stumbled upon this article: [DateTime precision with MongoDB and the C# Driver](https://alexmg.dev/posts/datetime-precision-with-mongodb-and-the-c-driver).

It explains how it's possible to mark a DateTime property with `[BsonDateTimeOptions(Representation = BsonType.Document)]`. When this is done, the property is serialized using the following representation: `"Timestamp": { "DateTime" : ISODate("2011-09-29T14:56:20.481Z"), "Ticks" : NumberLong("634529049804813857") }` (instead of directly serializing to ISODate like `"Timestamp" : ISODate("2011-09-29T14:44:49.172Z") }` 

In this case, one can use the Ticks property to deserialize the DateTime with full precision. But there seem to be some issues with querying data. So another way to implement this would be to emulate that behavior and serialize to the same document format, instead of using the string representation. 

It's probably more aligned with what MongoDB intended, but I'm not sure I like it that much as well... I think the Bson DateTime Handling is really bad :\

But basically there's now 3 ways to serialize DateTime in Bson:
* Directly using ISODate: Looses precision, is the most standard and straight forward way, no issues with querying data
* Use the `BsonType.Document` representation, storing as a combined property of Ticks and ISODate. Issues with querying, data is seperated. Weird format (more nested than one would assume)
* Serialize as string. keep the complete persistance but it's not an ISODate anymore. Full precision. Can't be queried as datetime

**Comment by tetious** [comment]
I did find that article and came to similar conclusions as you. It would work, and maybe it fits, but it just doesn't feel right.

It turns out many (most? all?) database systems have less precision than NodaTime (or .net DateTime). Even MS Sql! (though they have the non-default and lovingly named datetime2 with ns precision)

For this project, I'm motivated by what folks actually need, and if the string implementation works for you (and ms precision works for most others, I suspect) I think we can stick with two options.

By the way, Mongo's BSON library is SUPER annoying to work with. I'd originally planned to make a separate converter class instead of the weird static property thing. It turns out you can't test this sensibly, as converters in the BSON library are static, global and can't be replaced or deleted. There is probably a way to hack this with reflection or something, (or I might have missed something obvious or non-obvious) but I didn't have time to mess with it.

There isn't even a way to check if you've already registered a converter without it creating a default converter that you than can't replace. :|
